dist: xenial

branches:
  only:
    - master

language: c
cache: ccache

matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=3.5.8
    - os: linux
      env: PYTHON_VERSION=3.6.9
    - os: linux
      env: PYTHON_VERSION=3.7.1
    - os: linux
      env: PYTHON_VERSION=3.8.0
    - os: osx
      env: PYTHON_VERSION=3.5.8
    - os: osx
      env: PYTHON_VERSION=3.6.9
    - os: osx
      env: PYTHON_VERSION=3.7.1
    - os: osx
      env: PYTHON_VERSION=3.8.0

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      set -e;
      pushd /opt/pyenv;
      git pull origin master;
      popd;
      sudo apt-get update;
      sudo apt-get install ca-certificates;
      sudo sed -e '$s,$,\ndeb https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_16.04/ ./,' -i /etc/apt/sources.list;
      sudo curl 'https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_16.04/Release.key' > Release.key;
      sudo apt-key add Release.key;
      sudo apt-get update;
      sudo apt-get install libzmq3-dev libczmq-dev libczmq4 libzmq5;
      sudo pip install pipenv;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      set -e;
      brew update;
      brew install zeromq czmq;
      pip install pipenv;
      brew install ccache;
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
    fi
  # zyre v2.0.0 is as of this writing almost three years old, and numerous bug fixes have been merged.
  # Builds were failing using the default versions of zyre and czmq from ubuntu/homebrew, so we build from source
  - git clone git://github.com/zeromq/zyre.git $HOME/zyre;
  - cd $HOME/zyre;
  - ./autogen.sh;
  - ./configure;
  - make check;
  - sudo make install;
  - sudo ldconfig;
  - cd $TRAVIS_BUILD_DIR
  - pyenv install $PYTHON_VERSION --skip-existing;
  - pipenv install --dev --python $(pyenv prefix $PYTHON_VERSION)/bin/python;
  - pipenv run python bindings/generate.py
  - pipenv run python setup.py clean
  - pipenv run python setup.py build
  - pipenv run python setup.py install

script:
  - pipenv run python tests/__init__.py