dist: xenial

language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - sudo apt-get update
  - sudo apt-get install libzyre-dev libzmq3-dev libczmq-dev libzyre2 libczmq4 libzmq5
  - pip install tox

script:
  - tox