dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=3.5.8
    - os: linux
      env: PYTHON_VERSION=3.6.9
    - os: linux
      env: PYTHON_VERSION=3.7.1
    - os: linux
      env: PYTHON_VERSION=3.8.0
    - os: osx
      env: PYTHON_VERSION=3.5.8
    - os: osx
      env: PYTHON_VERSION=3.6.9
    - os: osx
      env: PYTHON_VERSION=3.7.1
    - os: osx
      env: PYTHON_VERSION=3.8.0

install:
  - pushd /opt/pyenv && git pull origin master; popd
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      set -e;
      sudo apt-get update;
      sudo apt-get install ca-certificates;
      sudo sed -e '$s,$,\ndeb https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_16.04/ ./,' -i /etc/apt/sources.list;
      sudo curl 'https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_16.04/Release.key' > Release.key;
      sudo apt-key add Release.key;
      sudo apt-get update;
      sudo apt-get install libzyre-dev libzmq3-dev libczmq-dev libzyre2 libczmq4 libzmq5;
      sudo pip install pipenv;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      set -e;
      brew update;
      brew install zeromq czmq zyre pyenv;
      pyenv install $PYTHON_VERSION;
      pip install pipenv;
    fi


script:
  - pyenv install $PYTHON_VERSION
  - pipenv install --dev --python $(pyenv prefix $PYTHON_VERSION)/bin/python;
  - pipenv run python bindings/generate.py
  - pipenv run python setup.py develop --uninstall
  - pipenv run python setup.py clean
  - pipenv run python setup.py build
  - pipenv run python setup.py develop
  - pipenv run python tests/__init__.py