dist: xenial

branches:
  only:
    - master

language: c
cache:
  - ccache
  - pip
  - directories:
    - /opt/python

matrix:
  include:
    - os: linux
      env: PYENV_VERSION=3.6.4
    - os: linux
      env: PYENV_VERSION=3.7.0
    - os: linux
      env: PYENV_VERSION=3.8.0
    - os: osx
      env: PYENV_VERSION=3.6.4
    - os: osx
      env: PYENV_VERSION=3.7.0
    - os: osx
      env: PYENV_VERSION=3.8.0

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
#        sudo apt-get update;
#        sudo apt-get install ca-certificates;
#        sudo sed -e '$s,$,\ndeb https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_16.04/ ./,' -i /etc/apt/sources.list;
#        sudo curl 'https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_16.04/Release.key' > Release.key;
#        sudo apt-key add Release.key;
#        sudo apt-get update;
#        sudo apt-get install libzmq3-dev libczmq-dev libczmq4 libzmq5 libzyre2 libzyre-dev;
        pushd /opt/pyenv;
        git pull origin master;
        popd;
        sudo pip install pipenv;
      fi
  - |
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
#        brew update;
#        brew install zeromq czmq zyre ccache;
        pip install pipenv;
        export PATH="/usr/local/opt/ccache/libexec:$PATH";
        ulimit -n 1200;
      fi

install:
  - cd $TRAVIS_BUILD_DIR
  - pyenv install $PYENV_VERSION --skip-existing;
  - pipenv install --dev --python $(pyenv prefix $PYENV_VERSION)/bin/python;
  - pipenv run python setup.py clean
  - pipenv run python setup.py build
  - pipenv run python setup.py install

script:
  - pipenv run python tests/__init__.py