dist: xenial

branches:
  only:
    - master

language: c
cache:
  - ccache
  - pip
  - directories:
    - $HOME/.pyenv_cache
    - .autoconf

matrix:
  include:
    - os: linux
      env: PYENV_VERSION=3.5.8
    - os: linux
      env: PYENV_VERSION=3.6.9
    - os: linux
      env: PYENV_VERSION=3.7.1
    - os: linux
      env: PYENV_VERSION=3.8.0
    - os: osx
      env: PYENV_VERSION=3.5.8
    - os: osx
      env: PYENV_VERSION=3.6.9
    - os: osx
      env: PYENV_VERSION=3.7.1
    - os: osx
      env: PYENV_VERSION=3.8.0

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        pushd /opt/pyenv;
        git pull origin master;
        popd;
        sudo pip install pipenv;
      fi
    - |
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update;
        pip install pipenv;
        brew install ccache;
        export PATH="/usr/local/opt/ccache/libexec:$PATH";
      fi

install:
  - git clone --single-branch --branch master git://github.com/zeromq/libzmq.git $HOME/libzmq;
  - cd $HOME/libzmq;
  - ./autogen.sh;
  - ./configure;
  - make check;
  - sudo make install;
  - which ldconfig && sudo ldconfig;

  - git clone --single-branch --branch master git://github.com/zeromq/czmq.git $HOME/czmq;
  - cd $HOME/czmq;
  - ./autogen.sh;
  - ./configure;
  - make check;
  - sudo make install;
  - which ldconfig && sudo ldconfig;

  - git clone --single-branch --branch master git://github.com/zeromq/zyre.git $HOME/zyre;
  - cd $HOME/zyre;
  - ./autogen.sh;
  - ./configure;
  - make check;
  - sudo make install;
  - which ldconfig && sudo ldconfig;

  - cd $TRAVIS_BUILD_DIR
  - pyenv install $PYENV_VERSION --skip-existing;
  - pipenv install --dev --python $(pyenv prefix $PYENV_VERSION)/bin/python;
  - pipenv run python bindings/generate.py
  - pipenv run python setup.py clean
  - pipenv run python setup.py build
  - pipenv run python setup.py install

script:
  - pipenv run python tests/__init__.py