dist: xenial

branches:
  only:
    - master

language: c
cache:
  - ccache
  - pip
  - directories:
    - /opt/python

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: osx
      env: PYENV_VERSION=3.5.8
    - os: osx
      env: PYENV_VERSION=3.6.9
    - os: osx
      env: PYENV_VERSION=3.7.1
    - os: osx
      python: 3.8

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get update;
        sudo apt-get install ca-certificates;
        sudo sed -e '$s,$,\ndeb https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_16.04/ ./,' -i /etc/apt/sources.list;
        sudo curl 'https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_16.04/Release.key' > Release.key;
        sudo apt-key add Release.key;
        sudo apt-get update;
        sudo apt-get install libzmq3-dev libczmq-dev libczmq4 libzmq5 libzyre2 libzyre-dev;
        pip install pipenv;
        cd $TRAVIS_BUILD_DIR;
        pipenv install --dev --python $(which python);
      fi
  - |
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update;
        brew install zeromq czmq zyre ccache;
        pip install pipenv;
        export PATH="/usr/local/opt/ccache/libexec:$PATH";
        pyenv install $PYENV_VERSION --skip-existing;
        cd $TRAVIS_BUILD_DIR;
        pipenv install --dev --python $(pyenv prefix $PYENV_VERSION)/bin/python;
      fi

install:
#  - git clone --single-branch --branch master git://github.com/zeromq/libzmq.git $HOME/libzmq;
#  - cd $HOME/libzmq;
#  - ./autogen.sh;
#  - ./configure;
#  - make
#  - make check || true;
#  - sudo make install;
#  - which ldconfig && sudo ldconfig;
#
#  - git clone --single-branch --branch master git://github.com/zeromq/czmq.git $HOME/czmq;
#  - cd $HOME/czmq;
#  - ./autogen.sh;
#  - ./configure;
#  - make
#  - make check || true;
#  - sudo make install;
#  - which ldconfig && sudo ldconfig;
#
#  - git clone --single-branch --branch master git://github.com/zeromq/zyre.git $HOME/zyre;
#  - cd $HOME/zyre;
#  - ./autogen.sh;
#  - ./configure;
#  - make
#  - make check || true;
#  - sudo make install;
#  - which ldconfig && sudo ldconfig;

  - pipenv run python setup.py clean
  - pipenv run python setup.py build
  - pipenv run python setup.py install

script:
  - pipenv run python tests/__init__.py